"use client";

import { useState } from "react";
import { ArrowLeft, ScrollText, Telescope, Folders } from "lucide-react";

import { useReports, useReport } from "@/lib/hooks";
import { useUI } from "@/lib/store";
import { cn, relTime } from "@/lib/utils";

import { ViewShell } from "./view-shell";

export function ReportsView() {
  const [openId, setOpenId] = useState<string | null>(null);
  if (openId) return <ReportDetail id={openId} onBack={() => setOpenId(null)} />;
  return <ReportsList onOpen={setOpenId} />;
}

function ReportsList({ onOpen }: { onOpen: (id: string) => void }) {
  const r = useReports();
  const rows = r.data?.data ?? [];
  const setInv = useUI((s) => s.setActiveInvestigation);
  const setCase = useUI((s) => s.setActiveCase);
  const setView = useUI((s) => s.setView);

  return (
    <ViewShell
      title="Reports"
      subtitle="Investigation and case reports. Investigation reports are sectioned JSON; case reports are markdown."
      actions={<span className="text-[11px] text-[var(--foreground-muted)]">{rows.length} reports</span>}
    >
      <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
        {rows.map((rep) => (
          <article key={rep.id} className="glass rounded-lg p-4">
            <header className="flex items-start justify-between gap-2">
              <div className="min-w-0">
                <div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] text-[var(--foreground-muted)]">
                  <ScrollText className="h-3 w-3 text-[var(--accent)]" />
                  {rep.source} · {rep.type}
                </div>
                <h3 className="mt-0.5 truncate text-[14px] font-medium text-[var(--foreground)]">{rep.title}</h3>
              </div>
              <span
                className={cn(
                  "rounded px-1.5 py-0.5 text-[10px] font-medium capitalize",
                  rep.status === "published"
                    ? "bg-[var(--accent-soft)] text-[var(--accent-strong)]"
                    : "bg-[var(--background-elev-2)] text-[var(--foreground-muted)]",
                )}
              >
                {rep.status}
              </span>
            </header>
            <div className="mt-2 flex flex-wrap items-center gap-3 text-[10px] text-[var(--foreground-muted)]">
              <span>{rep.findingCount} findings</span>
              <span>generated by {rep.generatedBy ?? "—"}</span>
              <span>{relTime(rep.updatedAt)}</span>
            </div>
            <div className="mt-3 flex items-center gap-2">
              <button
                type="button"
                onClick={() => onOpen(rep.id)}
                className="rounded border border-[var(--border)] bg-[var(--background-elev)] px-2.5 py-1 text-[11px] text-[var(--foreground)] hover:border-[var(--accent)]"
              >
                Open
              </button>
              {rep.investigation && (
                <button
                  type="button"
                  onClick={() => { setInv(rep.investigation!.id); setView("investigations"); }}
                  className="flex items-center gap-1 text-[10px] text-[var(--accent)] hover:underline"
                >
                  <Telescope className="h-3 w-3" />
                  {rep.investigation.title}
                </button>
              )}
              {rep.case && (
                <button
                  type="button"
                  onClick={() => { setCase(rep.case!.id); setView("cases"); }}
                  className="flex items-center gap-1 text-[10px] text-[var(--forensic)] hover:underline"
                >
                  <Folders className="h-3 w-3" />
                  {rep.case.caseNumber}
                </button>
              )}
            </div>
          </article>
        ))}
        {rows.length === 0 && !r.isLoading && (
          <div className="glass col-span-full rounded-lg p-6 text-center text-[12px] text-[var(--foreground-muted)]">
            No reports yet.
          </div>
        )}
      </div>
    </ViewShell>
  );
}

function ReportDetail({ id, onBack }: { id: string; onBack: () => void }) {
  const r = useReport(id);
  const rep = r.data?.data;

  if (r.isLoading) {
    return (
      <ViewShell title="Report">
        <div className="glass rounded-lg p-6 text-[12px] text-[var(--foreground-muted)]">Loading…</div>
      </ViewShell>
    );
  }
  if (!rep) {
    return (
      <ViewShell title="Report">
        <div className="glass rounded-lg p-6 text-[12px] text-[var(--danger)]">Not found.</div>
      </ViewShell>
    );
  }

  // Parse Argus-style sections if any.
  let sections: Array<{ heading?: string; body?: string }> = [];
  try {
    const parsed = JSON.parse(rep.sections);
    if (Array.isArray(parsed)) sections = parsed;
  } catch {
    // ignore parse errors — render content as plain markdown.
  }

  return (
    <ViewShell
      title={rep.title}
      subtitle={`${rep.source} report · ${rep.type} · ${rep.status}`}
      actions={
        <button
          type="button"
          onClick={onBack}
          className="flex items-center gap-1.5 rounded-md border border-[var(--border)] bg-[var(--background-elev)] px-2.5 py-1.5 text-[12px] text-[var(--foreground-muted)] hover:text-[var(--foreground)]"
        >
          <ArrowLeft className="h-3.5 w-3.5" /> Back
        </button>
      }
    >
      {sections.length > 0 && (
        <article className="glass space-y-4 rounded-lg p-5">
          {sections.map((s, i) => (
            <section key={i}>
              {s.heading && (
                <h3 className="mb-1 text-[13px] font-semibold text-[var(--foreground)]">{s.heading}</h3>
              )}
              <p className="whitespace-pre-wrap text-[12px] leading-relaxed text-[var(--foreground)]">{s.body ?? ""}</p>
            </section>
          ))}
        </article>
      )}
      {rep.content && (
        <article className="glass rounded-lg p-5">
          <pre className="whitespace-pre-wrap font-sans text-[12px] leading-relaxed text-[var(--foreground)]">
            {rep.content}
          </pre>
        </article>
      )}
    </ViewShell>
  );
}
